routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', function () {
	return view('home');
})->name('home')->middleware('auth');

Route::get('/selectOrganization','SelectOrganizationController@index')->name('selectOrganization')->middleware('web','auth');
Route::get('/selectOrganization/{id}','SelectOrganizationController@show')->middleware('web','auth');

Route::group(['prefix'=>'apps/settings', 'middleware' => ['web','auth','organization'] ], function () {

	Route::post('roles/editRolePermission', 'Admin\RolesController@editRolePermission');

	Route::resource('users', 'Admin\UsersController');
	Route::resource('roles', 'Admin\RolesController');
	Route::resource('permissions', 'Admin\PermissionsController');

});

Route::group(['prefix'=>'apps', 'middleware' => ['web','auth','organization'] ], function () {

	Route::get('assesment/cohort/cummulative', 'Assesment\CohortController@cummulative');
	Route::get('assesment/student/cummulative', 'Assesment\StudentController@cummulative');

	Route::resource('assesment/course', 'Assesment\CourseController');
	Route::resource('assesment/outcome', 'Assesment\OutcomeController');
	Route::resource('assesment/cohort', 'Assesment\CohortController');
	Route::resource('assesment/curriculum', 'Assesment\CurriculumController');
	Route::resource('assesment/student', 'Assesment\StudentController');

	Route::resource('curriculum/attainments', 'Curriculum\AttainmentsController');
	Route::resource('curriculum/curriculums', 'Curriculum\CurriculumsController');
	Route::resource('curriculum/competences', 'Curriculum\CompetencesController');
	Route::resource('curriculum/components', 'Curriculum\ComponentsController');
	Route::resource('curriculum/courses', 'Curriculum\CoursesController');
	Route::resource('curriculum/domains', 'Curriculum\DomainsController');
	Route::resource('curriculum/grades', 'Curriculum\GradesController');
	Route::resource('curriculum/imports', 'Curriculum\ImportsController');
	Route::resource('curriculum/levels', 'Curriculum\LevelsController');
	Route::resource('curriculum/objectives', 'Curriculum\ObjectivesController');
	Route::resource('curriculum/outcomes', 'Curriculum\OutcomesController');
	Route::resource('curriculum/performances', 'Curriculum\PerformancesController');

	Route::resource('learning/classes', 'Learning\ClassesController');

});

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">

    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>Dashboard</h2>
                </div>
                <div class="body">
                    <table class="table" style="font-weight: bold;">
                        <tr><td>Nama <td>:</td> </td><td>{{ Auth::user()->name }}</td></tr>
                        <tr><td>Email <td>:</td> </td><td>{{ Auth::user()->email }}</td></tr>
                        <tr>
                            <td>
                                Active Role <td>:</td> </td><td>{{ Auth::user()->roles[0]->display_name }}  ({{ session('organization_name') }})&nbsp;&nbsp;&nbsp; 
                                <a href="{{ route('selectOrganization') }}?redirect={{ Request::url() }}"><span class="label label-primary">Change Role</span></a>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>    

    <div class="row clearfix">

        <div class="col-lg-3 col-md-3 col-sm-4 col-xs-6">
            <div class="card card-clickable" url="{{ route('outcomes.index') }}">
                <div class="header bg-blue-grey">
                    <h2>Curriculums</h2>
                </div>
                <div class="body">
                    <i class="material-icons menu-icon">assignment</i>
                    <p>Manage an Objectives & Outcomes</p>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-3 col-sm-4 col-xs-6">
            <div class="card card-clickable" url="{{ route('classes.index') }}">
                <div class="header bg-blue-grey">
                    <h2>
                        Learning
                    </h2>
                </div>
                <div class="body">
                    <i class="material-icons menu-icon">school</i>
                    <p>Manage a classes,students and grades</p>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-3 col-sm-4 col-xs-6">
            <div class="card card-clickable" url="{{ route('outcome.index') }}">
                <div class="header bg-blue-grey">
                    <h2>Assesments</h2>
                </div>
                <div class="body">
                    <i class="material-icons menu-icon">assessment</i>
                    <p>Review progress with interactive charts</p>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-3 col-sm-4 col-xs-6">
            <div class="card card-clickable" url="{{ route('outcomes.index') }}">
                <div class="header bg-blue-grey">
                    <h2>
                        People and Organizations
                    </h2>
                </div>
                <div class="body">
                    <i class="material-icons menu-icon">group</i>
                    <p>Manage Study Program, etc</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        @permission("read-settings")
        <div class="col-lg-3 col-md-3 col-sm-4 col-xs-6">
            <div class="card card-clickable" url="{{ route('users.index') }}">
                <div class="header bg-blue-grey">
                    <h2>
                        Settings
                    </h2>
                </div>
                <div class="body">
                    <i class="material-icons menu-icon">settings</i>
                    <p>Manage Users, Role & Configuration</p>
                </div>
            </div>
        </div>
        @endpermission

    </div>
</div>

</div>
@endsection

@section('css')
<style>
.card-clickable {
    text-align: center;
}
.card-clickable:hover {
    cursor: pointer;
    opacity: 0.8;
}
.menu-icon {
    font-size: 10em;
}
</style>
@endsection

@section('js')
<script>
  $(document).ready(function(){
    var card = $(".card-clickable");

    card.click(function(){
      window.location.href = $(this).attr('url');
    });

  });
</script>    
@endsection

resources/views/profile.blade.php
@extends('layouts.app')

@section('content')

<div class="widget" style="margin-top:1em">
  <div class="widget-header"> <i class="icon-user"></i>
    <h3>Update Profile</h3>
  </div>
  <!-- /widget-header -->
  <div class="widget-content">

      {!! Form::model($data, ['url' => route('profiles.store'),'method'=>'post','class'=>'form-horizontal']) !!}

    <div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
      {!! Form::label('name', 'Name', ['class'=>'col-md-2 control-label']) !!}
      <div class="col-md-6">
        {!! Form::text('name', null, ['class'=>'form-control']) !!}
        {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
      </div>
    </div>

    <div class="form-group {{ $errors->has('username') ? 'has-error' : ''}}">
      {!! Form::label('username', 'Username', ['class'=>'col-md-2 control-label']) !!}
      <div class="col-md-6">
        {!! Form::text('username', null, ['class'=>'form-control']) !!}
        {!! $errors->first('username', '<p class="help-block">:message</p>') !!}
      </div>
    </div>

    <div class="form-group {{ $errors->has('email') ? 'has-error' : ''}}">
      {!! Form::label('email', 'Email', ['class'=>'col-md-2 control-label']) !!}
      <div class="col-md-6">
        {!! Form::email('email', null, ['rows'=>3,'class'=>'form-control']) !!}
        {!! $errors->first('email', '<p class="help-block">:message</p>') !!}
      </div>
    </div>
    <div class="form-group {{ $errors->has('password') ? 'has-error' : ''}}">
      {!! Form::label('password', 'Password', ['class'=>'col-md-2 control-label']) !!}
      <div class="col-md-6">
        {!! Form::text('password', null, ['class'=>'form-control','placeholder'=>'kosongkan jika tidak akan di ubah']) !!}
        {!! $errors->first('password', '<p class="help-block">:message</p>') !!}
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-2 col-md-offset-6" style="text-align: center">
        {!! Form::submit('Simpan', ['class'=> 'btn btn-primary']) !!}
      </div>
    </div>

    {!! Form::close() !!}

  </div>
  <!-- /widget-content --> 
</div>
<!-- /widget --> 

@endsection


@section('css')
<link rel="stylesheet" type="text/css" href="{{ asset('css/datatables.min.css') }}">
@endsection

@section('js')
<script src="{{ asset('js/datatables.min.js') }}"></script>
@endsection

resources/views/selectOrganization.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">

  <div class="row clearfix">

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

      <div class="card">

        <ol class="breadcrumb breadcrumb-bg-blue-grey">
          <li><a href="/"><i class="material-icons">home</i> Home</a></li>
          <li class="active">Select Role & Organization</li>
        </ol>

        <div class="body">
          <table class="table table-hover" id="konten"></table>
        </div>

      </div>
    </div>
  </div>
</div>

</div>
@endsection

@section('css')
<!-- JQuery DataTable Css -->
<link href="{{ asset('plugins') }}/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet">
<link href="{{ asset('plugins') }}/sweetalert/sweetalert.css" rel="stylesheet" />
@endsection

@section('js')

<!-- Jquery DataTable Plugin Js -->
<script src="{{ asset('plugins') }}/jquery-datatable/jquery.dataTables.js"></script>
<script src="{{ asset('plugins') }}/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>

<script>

  var urlParams = new URLSearchParams(window.location.search);
  var redirectUrl = urlParams.get('redirect');

  var table = $('#konten').DataTable({
    processing: true,
    serverSide: true,
    ajax: '',
    columns: [
      { data: 'no', name: 'no', searchable:false },
      { data: 'abbreviation', name: 'abbreviation', title:'Abbreviation' },
      { data: 'organization', name: 'organization', title:'Organizations' },
      @if(!\Auth::user()->hasRole('admin'))
      { data: 'display_name', name: 'display_name', title:'Role' },
      @endif
      { data: 'id', name: 'id', sortable: false,
          render: function(data) {
            return '<a href="{{ route('selectOrganization') }}/'+data+'?redirect='+redirectUrl+'"><button class="btn btn-primary btn-xs">Select</button></a>';
          }
      }
    ],
    responsive: true
  });
</script>
@endsection