routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', function () {
	return view('home');
})->name('home')->middleware('auth');

Route::get('/selectOrganization','SelectOrganizationController@index')->name('selectOrganization')->middleware('web','auth');
Route::get('/selectOrganization/{id}','SelectOrganizationController@show')->middleware('web','auth');

Route::group(['prefix'=>'apps/settings', 'middleware' => ['web','auth','organization'] ], function () {

	Route::post('roles/editRolePermission', 'Admin\RolesController@editRolePermission');

	Route::resource('users', 'Admin\UsersController');
	Route::resource('roles', 'Admin\RolesController');
	Route::resource('permissions', 'Admin\PermissionsController');

});

Route::group(['prefix'=>'apps', 'middleware' => ['web','auth','organization'] ], function () {

	Route::get('assesment/cohort/cummulative', 'Assesment\CohortController@cummulative');
	Route::get('assesment/student/cummulative', 'Assesment\StudentController@cummulative');

	Route::resource('assesment/course', 'Assesment\CourseController');
	Route::resource('assesment/outcome', 'Assesment\OutcomeController');
	Route::resource('assesment/cohort', 'Assesment\CohortController');
	Route::resource('assesment/curriculum', 'Assesment\CurriculumController');
	Route::resource('assesment/student', 'Assesment\StudentController');

	Route::resource('curriculum/attainments', 'Curriculum\AttainmentsController');
	Route::resource('curriculum/curriculums', 'Curriculum\CurriculumsController');
	Route::resource('curriculum/competences', 'Curriculum\CompetencesController');
	Route::resource('curriculum/components', 'Curriculum\ComponentsController');
	Route::resource('curriculum/courses', 'Curriculum\CoursesController');
	Route::resource('curriculum/domains', 'Curriculum\DomainsController');
	Route::resource('curriculum/grades', 'Curriculum\GradesController');
	Route::resource('curriculum/imports', 'Curriculum\ImportsController');
	Route::resource('curriculum/levels', 'Curriculum\LevelsController');
	Route::resource('curriculum/objectives', 'Curriculum\ObjectivesController');
	Route::resource('curriculum/outcomes', 'Curriculum\OutcomesController');
	Route::resource('curriculum/performances', 'Curriculum\PerformancesController');

	Route::resource('learning/classes', 'Learning\ClassesController');

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use LaratrustUserTrait;
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username','name', 'email', 'password', 'is_active', 'idnumber','prefix','suffix', 'birth_place', 'birth_date', 'active_role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\User;
use App\AssetDetail;
use Yajra\DataTables\DataTables;
use Illuminate\Support\Facades\Session;
use DB;
use Auth;
use Jackiedo\DotenvEditor\Facades\DotenvEditor;


class UsersController extends \App\Http\Controllers\Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {

            DB::statement(DB::raw('set @rownum=0'));
            $data = User::select(DB::raw('@rownum  := @rownum  + 1 AS no'),'users.*');

            if ($request->input('type')) {
                $data->join('role_user','role_user.user_id','users.id');
                $data->join('roles','role_user.role_id','roles.id');
                $data->where('roles.name',$request->input('type'));

                if ($request->input('angkatan')) {
                    $data->where(DB::raw('MID(users.noid,4,2)'),substr($request->input('angkatan'), 2));
                }
            }

            return Datatables::of($data)->make(true);
        }

        return view('users.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.form');
    }


    public function setFBP(Request $request)
    {
        $fileenv = DotenvEditor::load();
        $fileenv->setKey('APP_SASPRA',$request->input('saspra'));
        $fileenv->setKey('APP_PERPUS',$request->input('perpus'));
        $fileenv->setKey('APP_PRODI',$request->input('prodi'));
        $fileenv->save();

        return 'ok';
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->input('import')) {
            $import = json_decode($request->input('import'));


            foreach ($import as $key => $value) {
                $tmp = (array) $value;
                $tmp['password'] = bcrypt($tmp['password']);
                $tmp['desc'] = json_encode($tmp['desc']);
                $db = User::create($tmp);
                $db->attachRole($request->input('role'));
            }

            return 'ok';
        }

        $this->validate($request, [
            'username' => 'required|unique:users,username',
            'name' => 'required',
            'password' => 'required',
            'role' => 'required',
            'email' => 'required|email|unique:users,email',
            'is_active' => 'required|numeric',
        ]);

        $data = $request->all();
        $data['password'] = bcrypt($data['password']);
        $db = User::create($data);

        $db->attachRole($request->input('role'));

        Session::flash("status", [
            "level"=>"success",
            "message"=>"Berhasil Di Simpan"
        ]);

        return redirect()->route('users.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id,Request $request)
    {

        $data = User::find($id);
        $detail = AssetDetail::select('asset_details.*',DB::raw('IF(asset_details.condition=0 ,"Baik",IF(asset_details.condition=1,"Rusak Ringan","Rusak Berat")) AS conditionText'), 'rooms.name as roomName', 'assets.name')
            ->join('assets','assets.id','asset_details.asset_id')
            ->join('users','users.id','asset_details.user_id')
            ->leftJoin('rooms','rooms.id','asset_details.room_id')
            ->where('asset_details.user_id',$id)->get();

        $fileenv = DotenvEditor::load();
        $saspra = $fileenv->getValue('APP_SASPRA');
        $perpus = $fileenv->getValue('APP_PERPUS');
        $prodi = $fileenv->getValue('APP_PRODI');

        $output = [
            'data'=>$data,
            'detail'=>$detail,
            'saspra'=>$saspra,
            'perpus'=>$perpus,
            'prodi'=>$prodi,
        ];


        //response section
        if (Auth::check()) {
            if (Auth::user()->can('read-users') || Auth::user()->can('read-mahasiswa')) {

                if ($request->ajax()) {
                    //form bebas pinjam check
                    $cek = assetDetail::where('user_id',$id)->get();

                    if (count($cek) > 0) {
                        return 'not-ok';
                    }

                    return $output;
                }

                return view('users.show',$output);
            } else {
                return view('users.showPublic',$output);
                
            }
        }
        else {
            return view('users.showPublic',$output);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = User::select('users.id','users.name','users.username','users.is_active','users.email','users.desc','roles.id as role')
                ->join('role_user','role_user.user_id','users.id')
                ->join('roles','role_user.role_id','roles.id')
                ->find($id);

        return view('users.form')->with(compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'username' => 'required|unique:users,username,'.$id,
            'name' => 'required',
            'password' => 'nullable',
            'email' => 'required|email|unique:users,email,'.$id,
            'is_active' => 'required|numeric',
        ]);

        if ($request->input('password') == null) {
            $data = $request->except('password');
        } else {
            $data = $request->all();
            $data['password'] = bcrypt($data['password']);
        }

        if ($request->input('role') == 4) { //for mahasiswa

            $desc = [
                'wali' => $data['wali'],
                'pembimbing1' => $data['pembimbing1'],
                'pembimbing2' => $data['pembimbing2'],
                'plab' => $data['plab'],
                'lab' => $data['lab'],
                'wisuda' => $data['wisuda'],
            ];

            $data['desc'] = json_encode($desc);
        }

        $db = User::select('users.*','roles.id as role')
                ->join('role_user','role_user.user_id','users.id')
                ->join('roles','role_user.role_id','roles.id')
                ->find($id);

        $db->detachRole($db->role);

        $db->update($data);
        $db->attachRole($request->input('role'));

        Session::flash("status", [
            "level"=>"success",
            "message"=>"Berhasil Di Simpan"
        ]);

        if ($request->input('role') == 4) { //for mahasiswa

            return redirect()->route('mahasiswa');

        }

        return redirect()->route('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $db = User::find($id);
        $db->delete();

        Session::flash("status", [
            "level"=>"danger",
            "message"=>"Berhasil Di Hapus"
        ]);

        return 'ok';
    }
}

resources/views/users/dosen.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
  <div class="block-header">
    <h2>Manajemen Pengguna</h2>
  </div>
  <!-- Basic Table -->
  <div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="header bg-blue-grey">
          <h2>
            List Dosen
          </h2>
          <ul class="header-dropdown m-r--5">
            <li class="dropdown">
              <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <i class="material-icons">more_vert</i>
              </a>
              <ul class="dropdown-menu pull-right">
              @if(\Laratrust::can("create-dosen"))
                <li><a href="{{ route('users.create') }}">Tambah</a></li>
              @endif
              </ul>
            </li>
          </ul>
        </div>
        <div class="body table-responsive">
          <table class="table" id="users-table">
            <thead>
              <tr>
                <th>#</th>
                <th>Nip</th>
                <th>Name</th>
                <th>Username</th>
                <th>Email</th>
                <th>Is Active</th>
                <th>Action</th>
              </tr>
            </thead>
          </table>

        </div>
      </div>
    </div>
  </div>
  <!-- #END# Basic Table -->

</div>

@endsection


@section('css')
<!-- JQuery DataTable Css -->
<link href="{{ asset('plugins') }}/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet">
<!-- Sweetalert Css -->
<link href="{{ asset('plugins') }}/sweetalert/sweetalert.css" rel="stylesheet" />
@endsection

@section('js')

<!-- Jquery DataTable Plugin Js -->
<script src="{{ asset('plugins') }}/jquery-datatable/jquery.dataTables.js"></script>
<script src="{{ asset('plugins') }}/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
<script src="{{ asset('plugins') }}/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
<script src="{{ asset('plugins') }}/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
<script src="{{ asset('plugins') }}/jquery-datatable/extensions/export/jszip.min.js"></script>
<script src="{{ asset('plugins') }}/jquery-datatable/extensions/export/pdfmake.min.js"></script>
<script src="{{ asset('plugins') }}/jquery-datatable/extensions/export/vfs_fonts.js"></script>
<script src="{{ asset('plugins') }}/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
<script src="{{ asset('plugins') }}/jquery-datatable/extensions/export/buttons.print.min.js"></script>

<!-- SweetAlert Plugin Js -->
<script src="{{ asset('plugins') }}/sweetalert/sweetalert.min.js"></script>
<script>

  var showPath = '{{ route("dosen.show",'') }}';
  var editPath = '{{ url("/settings/users/") }}';
  var deletePath =  '{{ route("users.destroy",'') }}';
  var addPath =  '{{ route("users.create") }}';

  $(function() {

    function genEditPath(id) {
      return editPath+'/'+id+'/edit';
    }

    function genShowPath(id) {
      return showPath+'/'+id;
    }


    $('#users-table').DataTable({
      processing: true,
      serverSide: true,
      ajax: '{!! route('users.index') !!}'+'?type=dosen',
      columns: [
      { data: 'no', name: 'no', searchable: false},
      { data: 'noid', name: 'noid' },
      { data: 'name', name: 'name' },
      { data: 'username', name: 'username' },
      { data: 'email', name: 'email' },
      { data: 'is_active', name: 'is_active' , searchable: false,render: function(data) {
        if (data == 1) {
          return '<span class="btn btn-xs btn-success">Active</span>';
        } else {
          return '<span class="btn btn-xs btn-danger">Disabled</span>';
        }
      }},
      { data: 'id', name: 'id', sortable: false,render: function(data) {
        return '<a href="'+genShowPath(data)+'"><button class="btn btn-success btn-xs">Lihat</button></a> @if(\Laratrust::can("update-dosen")) <a href="'+genEditPath(data)+'"><button class="btn btn-primary btn-xs">Ubah</button></a>@endif @if(\Laratrust::can("delete-dosen")) <button onclick="deleteData('+data+')" class="btn btn-danger btn-xs">Hapus</button> @endif';
      }},
      ],
      dom: 'Bfrtip',
      responsive: true,
      buttons: [
      {
        extend: 'excel',
        className: 'btn btn-xs',
        text: '<i class="material-icons">print</i>'
      }@if(\Laratrust::can("create-dosen")),
      {
        text: '<i class="material-icons">add</i>',
        className: 'btn btn-xs',
        action: function () {
          window.location.href = addPath;
        }
      }
      @endif
      ]
    });
  });

  @if(\Laratrust::can("delete-dosen"))
  function deleteData(id) {
    swal({
        title: "Apakah Anda Yakin ?",
        text: "Data akan Hilang Setelah Di Hapus!",
        type: "warning",
        showCancelButton: true,
        confirmButtonColor: "#DD6B55",
        confirmButtonText: "Ya, Hapus!",
        closeOnConfirm: false
    }, function() {
        sendAjax();
    } );

    function sendAjax() {
      $.ajax({
        url: deletePath+'/'+id,
        data: { '_token': '{{ csrf_token() }}' },
        type: 'DELETE',
        error: function() {
          alert('error');
        },
        success: function(res) {
            swal({
              title: "Berhasil Di Hapus!",
              text: "Data Telah Berhasil Di Hapus",
              type: "success"
            }, function() {
              location.reload();
            });
        }
      }); 
    }
  }
  @endif

</script>
@endsection

resources/views/users/form.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
  <div class="block-header">
    <h2>Manajemen Pengguna</h2>
  </div>

  <!-- Horizontal Layout -->
  <div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="header">
          <h2>
            @if(isset($data))
            Edit Pengguna
            @else
            Tambah Pengguna
            @endif

          </h2>
        </div>
        <div class="body">

            @if(isset($data))
              {!! Form::model($data, ['url' => route('users.update', $data->id), 'files'=>true,'method'=>'put','class'=>'form-horizontal']) !!}
            @else
              {!! Form::open(['url' => route('users.store'), 'method' => 'post','files'=>true, 'class'=>'form-horizontal']) !!}
            @endif

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="name">Name</label>
              </div>
              <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                <div class="form-group">
                  <div class="form-line{{ $errors->has('name') ? ' error' : '' }}">
                    {!! Form::text('name', null, ['class'=>'form-control']) !!}
                  </div>
                  @if ($errors->has('name'))
                      <label class="error" for="name">
                          {{ $errors->first('name') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="username">Username</label>
              </div>
              <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                <div class="form-group">
                  <div class="form-line{{ $errors->has('username') ? ' error' : '' }}">
                    {!! Form::text('username', null, ['class'=>'form-control']) !!}
                  </div>
                  @if ($errors->has('username'))
                      <label class="error" for="username">
                          {{ $errors->first('username') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="email">Email</label>
              </div>
              <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                <div class="form-group">
                  <div class="form-line{{ $errors->has('email') ? ' error' : '' }}">
                    {!! Form::email('email', null, ['class'=>'form-control']) !!}
                  </div>
                  @if ($errors->has('email'))
                      <label class="error" for="email">
                          {{ $errors->first('email') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="phone">Phone</label>
              </div>
              <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                <div class="form-group">
                  <div class="form-line{{ $errors->has('phone') ? ' error' : '' }}">
                    {!! Form::number('phone', null, ['class'=>'form-control']) !!}
                  </div>
                  @if ($errors->has('phone'))
                      <label class="error" for="phone">
                          {{ $errors->first('phone') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>


          @if($data->role == 4)
          @php
            $desc = json_decode($data->desc); 
          @endphp

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="wali">Wali</label>
              </div>
              <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                <div class="form-group">
                  <div class="form-line{{ $errors->has('wali') ? ' error' : '' }}">
                    {!! Form::text('wali', $desc->wali, ['class'=>'form-control']) !!}
                  </div>
                  @if ($errors->has('wali'))
                      <label class="error" for="wali">
                          {{ $errors->first('wali') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="pembimbing1">Pembimbing 1</label>
              </div>
              <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                <div class="form-group">
                  <div class="form-line{{ $errors->has('pembimbing1') ? ' error' : '' }}">
                    {!! Form::text('pembimbing1', $desc->pembimbing1, ['class'=>'form-control']) !!}
                  </div>
                  @if ($errors->has('pembimbing1'))
                      <label class="error" for="pembimbing1">
                          {{ $errors->first('pembimbing1') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="pembimbing2">Pembimbing2</label>
              </div>
              <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                <div class="form-group">
                  <div class="form-line{{ $errors->has('pembimbing2') ? ' error' : '' }}">
                    {!! Form::text('pembimbing2', $desc->pembimbing2, ['class'=>'form-control']) !!}
                  </div>
                  @if ($errors->has('pembimbing2'))
                      <label class="error" for="pembimbing2">
                          {{ $errors->first('pembimbing2') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="lab">Lab</label>
              </div>
              <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                <div class="form-group">
                  <div class="form-line{{ $errors->has('lab') ? ' error' : '' }}">
                    {!! Form::text('lab', $desc->lab, ['class'=>'form-control']) !!}
                  </div>
                  @if ($errors->has('lab'))
                      <label class="error" for="lab">
                          {{ $errors->first('lab') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="plab">Penanggung Jawab Lab</label>
              </div>
              <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                <div class="form-group">
                  <div class="form-line{{ $errors->has('plab') ? ' error' : '' }}">
                    {!! Form::text('plab', $desc->plab, ['class'=>'form-control']) !!}
                  </div>
                  @if ($errors->has('plab'))
                      <label class="error" for="plab">
                          {{ $errors->first('plab') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="wisuda">Wisuda</label>
              </div>
              <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                <div class="form-group">
                  <div class="form-line{{ $errors->has('wisuda') ? ' error' : '' }}">
                    {!! Form::text('wisuda', $desc->wisuda, ['class'=>'form-control']) !!}
                  </div>
                  @if ($errors->has('wisuda'))
                      <label class="error" for="wisuda">
                          {{ $errors->first('wisuda') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>
          @endif


            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="password">Password</label>
              </div>
              <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                <div class="form-group">
                  <div class="form-line{{ $errors->has('password') ? ' error' : '' }}">
                    {!! Form::text('password', null, ['class'=>'form-control']) !!}
                  </div>
                  @if ($errors->has('password'))
                      <label class="error" for="password">
                          {{ $errors->first('password') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="address">Address</label>
              </div>
              <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                <div class="form-group">
                  <div class="form-line{{ $errors->has('address') ? ' error' : '' }}">
                    {!! Form::textarea('address', null, ['class'=>'form-control']) !!}
                  </div>
                  @if ($errors->has('address'))
                      <label class="error" for="address">
                          {{ $errors->first('address') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="role">Role</label>
              </div>
              <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                <div class="form-group">
                  <div class="form-line{{ $errors->has('role') ? ' error' : '' }}">
                    {!! Form::select('role', App\Role::pluck('display_name','id')->all(), null, ['class' => 'form-control show-tick', 'placeholder'=>'Pilih role'] ) !!}
                  </div>
                  @if ($errors->has('role'))
                      <label class="error" for="role">
                          {{ $errors->first('role') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="is_active">Mode</label>
              </div>
              <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                <div class="form-group">
                  <div class="form-line{{ $errors->has('is_active') ? ' error' : '' }}">
                    {!! Form::select('is_active', ['1'=>'Active','0'=>'Disabled'], null, ['class' => 'form-control'] ) !!}
                  </div>
                  @if ($errors->has('is_active'))
                      <label class="error" for="is_active">
                          {{ $errors->first('is_active') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>

            <div class="row clearfix">
              <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                <input type="submit" class="btn btn-primary m-t-15 waves-effect" value="Simpan">
              </div>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- #END# Horizontal Layout -->

</div>
@endsection

@section('css')
<link href="{{ asset('plugins') }}/bootstrap-select/css/bootstrap-select.css" rel="stylesheet">
@endsection