routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', function () {
	return view('home');
})->name('home')->middleware('auth');

Route::get('/selectOrganization','SelectOrganizationController@index')->name('selectOrganization')->middleware('web','auth');
Route::get('/selectOrganization/{id}','SelectOrganizationController@show')->middleware('web','auth');

Route::group(['prefix'=>'apps/settings', 'middleware' => ['web','auth','organization'] ], function () {

	Route::post('roles/editRolePermission', 'Admin\RolesController@editRolePermission');

	Route::resource('users', 'Admin\UsersController');
	Route::resource('roles', 'Admin\RolesController');
	Route::resource('permissions', 'Admin\PermissionsController');

});

Route::group(['prefix'=>'apps', 'middleware' => ['web','auth','organization'] ], function () {

	Route::get('assesment/cohort/cummulative', 'Assesment\CohortController@cummulative');
	Route::get('assesment/student/cummulative', 'Assesment\StudentController@cummulative');

	Route::resource('assesment/course', 'Assesment\CourseController');
	Route::resource('assesment/outcome', 'Assesment\OutcomeController');
	Route::resource('assesment/cohort', 'Assesment\CohortController');
	Route::resource('assesment/curriculum', 'Assesment\CurriculumController');
	Route::resource('assesment/student', 'Assesment\StudentController');

	Route::resource('curriculum/attainments', 'Curriculum\AttainmentsController');
	Route::resource('curriculum/curriculums', 'Curriculum\CurriculumsController');
	Route::resource('curriculum/competences', 'Curriculum\CompetencesController');
	Route::resource('curriculum/components', 'Curriculum\ComponentsController');
	Route::resource('curriculum/courses', 'Curriculum\CoursesController');
	Route::resource('curriculum/domains', 'Curriculum\DomainsController');
	Route::resource('curriculum/grades', 'Curriculum\GradesController');
	Route::resource('curriculum/imports', 'Curriculum\ImportsController');
	Route::resource('curriculum/levels', 'Curriculum\LevelsController');
	Route::resource('curriculum/objectives', 'Curriculum\ObjectivesController');
	Route::resource('curriculum/outcomes', 'Curriculum\OutcomesController');
	Route::resource('curriculum/performances', 'Curriculum\PerformancesController');

	Route::resource('learning/classes', 'Learning\ClassesController');

});

app/Models/Curriculum.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Curriculum extends Model
{
    protected $table = 'pc_curriculums';

    protected $fillable = [
        'domain','description','created_at','updated_at'
    ];
}

app/Http/Controllers/Assesment/CurriculumController.php
<?php

namespace App\Http\Controllers\Assesment;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;
use App\Models\Curriculum;

class CurriculumController extends Controller
{

    private $program_id = 1;

    private $curriculums;

    public function __construct()
    {
      $this->curriculums = Curriculum::select('po_organizations.organization','pc_curriculums.id','pc_curriculums.title')
                          ->join('pc_programs','pc_programs.id','pc_curriculums.program_id')
                          ->join('po_organizations','po_organizations.id','pc_programs.organization_id')
                          ->where('program_id',$this->program_id)
                          ->orderBy('pc_curriculums.id','DESC')
                          ->orderBy('po_organizations.organization','ASC')
                          ->get();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      return view('assesment/curriculum', ['curriculums' => $this->curriculums ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $result = DB::table('pc_outcomes')
          ->select(DB::raw('pc_outcomes.code as outcome, smt, pc_courses.code as code, pc_courses.title_en as course, pa_directs.year, a1, a2, a3, a4'))
          ->join('pa_directs','pc_outcomes.id','pa_directs.outcome_id')
          ->join('pc_courses','pa_directs.course_id','pc_courses.id')
          ->orderBy('outcome', 'ASC')
          ->orderBy('smt', 'ASC')
          ->orderBy('pa_directs.code', 'ASC')
          ->orderBy('pa_directs.year', 'ASC')
          ->where('pc_outcomes.curriculum_id','=',$id)
          ->get();
        return response()->json($result);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

}

app/Http/Controllers/Assesment/OutcomeController.php
<?php

namespace App\Http\Controllers\Assesment;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;




class OutcomeController extends Controller
{

    private $curriculum_id = 2;

    private $outcomes;

    public function __construct () {
      $this->outcomes = DB::table('pc_outcomes')
        ->select('pc_outcomes.*')
        ->where('pc_outcomes.curriculum_id','=', $this->curriculum_id)
        ->get();

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      return view('assesment/outcome', [ 'outcomes' => $this->outcomes ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        $result = DB::table('pc_outcomes')
          ->select(DB::raw('pc_outcomes.code as outcome, smt, pc_courses.code as code, pc_courses.title_en as course, pa_directs.year, a1, a2, a3, a4'))
          ->join('pa_directs','pc_outcomes.id','pa_directs.outcome_id')
          ->join('pc_courses','pa_directs.course_id','pc_courses.id')
          ->orderBy('outcome', 'ASC')
          ->orderBy('smt', 'ASC')
          ->orderBy('pa_directs.code', 'ASC')
          ->orderBy('pa_directs.year', 'ASC')
          ->where('pc_outcomes.id','=', $id)
          ->get();
        return response()->json($result);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

}

app/Http/Controllers/Curriculum/AttainmentsController.php
<?php

namespace App\Http\Controllers\Curriculum;

use Illuminate\Http\Request;
use App\Models\Attainment;
use App\Models\Curriculum;

use Yajra\DataTables\DataTables;
use Illuminate\Support\Facades\Session;
use DB;

class AttainmentsController extends \App\Http\Controllers\Controller
{


    private $validationRule = [
        'curriculum_id' => 'required|exists:pc_curriculums,id',
        'title' => 'required|between:1,100',
        'attainment' => 'required|integer|between:1,10',
        'treshold' => 'required|integer|between:1,100',
        'description' => 'required|between:1,240'
    ];

    public function index(Request $request)
    {
        $organization_id = $request->session()->get('organization_id');

        $curriculums = Curriculum::select('po_organizations.organization','pc_curriculums.id','pc_curriculums.title')
                        ->join('pc_programs','pc_programs.id','pc_curriculums.program_id')
                        ->join('po_organizations','po_organizations.id','pc_programs.organization_id')
                        ->where('po_organizations.id',$organization_id)
                        ->orderBy('pc_curriculums.id','DESC')
                        ->orderBy('po_organizations.organization','ASC')
                        ->get();

        if ($request->ajax()) {
            if(count($curriculums) > 0) {
                $curriculum_id = isset($_GET['id']) ? e($_GET['id']) : $curriculums[0]->id;
            } else {
                $curriculum_id = 0;
            }

            DB::statement(DB::raw('set @rownum=0'));

            $data = Attainment::select(DB::raw('@rownum  := @rownum  + 1 AS no'),'pc_attainments.*')
                            ->where('pc_attainments.curriculum_id',$curriculum_id);
            return Datatables::of($data)->make(true);
        }

        return view('curriculum.attainments.index',[ 'curriculums' => $curriculums ]);
    }

    public function create()
    {
        $organization_id = session()->get('organization_id');

        $curriculums = Curriculum::select('po_organizations.organization','pc_curriculums.id','pc_curriculums.title')
                        ->join('pc_programs','pc_programs.id','pc_curriculums.program_id')
                        ->join('po_organizations','po_organizations.id','pc_programs.organization_id')
                        ->where('po_organizations.id',$organization_id)
                        ->orderBy('pc_curriculums.id','DESC')
                        ->pluck('title','id');

        return view('curriculum.attainments.form',[ 
            'curriculum_id' => $curriculums, 
        ]);
    }

    public function store(Request $request)
    {
        $this->validate($request, $this->validationRule);

        $data = $request->all();

        $db = Attainment::create($data);

        Session::flash("status", [
            "level"=>"success",
            "message"=>"Data has been saved"
        ]);

        return redirect()->route('attainments.index');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $data = Attainment::find($id);

        $organization_id = session()->get('organization_id');

        $curriculums = Curriculum::select('po_organizations.organization','pc_curriculums.id','pc_curriculums.title')
                        ->join('pc_programs','pc_programs.id','pc_curriculums.program_id')
                        ->join('po_organizations','po_organizations.id','pc_programs.organization_id')
                        ->where('po_organizations.id',$organization_id)
                        ->orderBy('pc_curriculums.id','DESC')
                        ->pluck('title','id'); 
                               
        return view('curriculum.attainments.form', [ 
            'curriculum_id' => $curriculums,
            'data' => $data,
        ]);
    }

    public function update(Request $request, $id)
    {

        $this->validate($request, $this->validationRule);

        $data = $request->all();

        $db = Attainment::find($id);

        $db->update($data);

        Session::flash("status", [
            "level"=>"success",
            "message"=>"Data has been updated"
        ]);

        return redirect()->route('attainments.index');
    }

    public function destroy($id)
    {
        $db = Attainment::find($id);
        $db->delete();

        Session::flash("status", [
            "level"=>"danger",
            "message"=>"Data has been deleted"
        ]);

        return 'ok';
    }

}

app/Http/Controllers/Curriculum/ComponentsController.php
<?php

namespace App\Http\Controllers\Curriculum;

use Illuminate\Http\Request;
use App\Models\Component;
use App\Models\Curriculum;

use Yajra\DataTables\DataTables;
use Illuminate\Support\Facades\Session;
use DB;

class ComponentsController extends \App\Http\Controllers\Controller
{


    private $validationRule = [
        'curriculum_id' => 'required|exists:pc_curriculums,id',
        'code' => 'required|between:1,10',
        'component' => 'required|between:1,50',
        'description' => 'required|between:1,240'
    ];

    public function index(Request $request)
    {
        $organization_id = $request->session()->get('organization_id');

        $curriculums = Curriculum::select('po_organizations.organization','pc_curriculums.id','pc_curriculums.title')
                        ->join('pc_programs','pc_programs.id','pc_curriculums.program_id')
                        ->join('po_organizations','po_organizations.id','pc_programs.organization_id')
                        ->where('po_organizations.id',$organization_id)
                        ->orderBy('pc_curriculums.id','DESC')
                        ->orderBy('po_organizations.organization','ASC')
                        ->get();

        if ($request->ajax()) {
            if(count($curriculums) > 0) {
                $curriculum_id = isset($_GET['id']) ? e($_GET['id']) : $curriculums[0]->id;
            } else {
                $curriculum_id = 0;
            }

            DB::statement(DB::raw('set @rownum=0'));

            $data = Component::select(DB::raw('@rownum  := @rownum  + 1 AS no'),'pc_components.*')
                            ->where('pc_components.curriculum_id',$curriculum_id);

            if($request->has('draw')) {
                return Datatables::of($data)->make(true);
            }

            return $data->get();
        }

        return view('curriculum.components.index',[ 'curriculums' => $curriculums ]);
    }

    public function create()
    {
        $organization_id = session()->get('organization_id');

        $curriculums = Curriculum::select('po_organizations.organization','pc_curriculums.id','pc_curriculums.title')
                        ->join('pc_programs','pc_programs.id','pc_curriculums.program_id')
                        ->join('po_organizations','po_organizations.id','pc_programs.organization_id')
                        ->where('po_organizations.id',$organization_id)
                        ->orderBy('pc_curriculums.id','DESC')
                        ->pluck('title','id');

        return view('curriculum.components.form',[ 
            'curriculum_id' => $curriculums, 
        ]);
    }

    public function store(Request $request)
    {
        $this->validate($request, $this->validationRule);

        $data = $request->all();

        $db = Component::create($data);

        Session::flash("status", [
            "level"=>"success",
            "message"=>"Data has been saved"
        ]);

        return redirect()->route('components.index');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $data = Component::find($id);

        $organization_id = session()->get('organization_id');

        $curriculums = Curriculum::select('po_organizations.organization','pc_curriculums.id','pc_curriculums.title')
                        ->join('pc_programs','pc_programs.id','pc_curriculums.program_id')
                        ->join('po_organizations','po_organizations.id','pc_programs.organization_id')
                        ->where('po_organizations.id',$organization_id)
                        ->orderBy('pc_curriculums.id','DESC')
                        ->pluck('title','id'); 
                               
        return view('curriculum.components.form', [ 
            'curriculum_id' => $curriculums,
            'data' => $data,
        ]);
    }

    public function update(Request $request, $id)
    {

        $this->validate($request, $this->validationRule);

        $data = $request->all();

        $db = Component::find($id);

        $db->update($data);

        Session::flash("status", [
            "level"=>"success",
            "message"=>"Data has been updated"
        ]);

        return redirect()->route('components.index');
    }

    public function destroy($id)
    {
        $db = Component::find($id);
        $db->delete();

        Session::flash("status", [
            "level"=>"danger",
            "message"=>"Data has been deleted"
        ]);

        return 'ok';
    }

}

resources/views/curriculum/outcomes/form.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">

  <!-- Horizontal Layout -->
  <div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <ol class="breadcrumb breadcrumb-bg-blue-grey">
          <li><a href="/"><i class="material-icons">home</i> Home</a></li>
          <li><a href="{{ route('outcomes.index') }}">Outcomes</a></li>
          <li class="active">Add New Outcomes</li>
        </ol>

        <div class="body">
            @if(isset($data))
              {!! Form::model($data, ['url' => route('outcomes.update', $data->id), 'files'=>true,'method'=>'put','class'=>'form-horizontal']) !!}
            @else
              {!! Form::open(['url' => route('outcomes.store'), 'method' => 'post','files'=>true, 'class'=>'form-horizontal']) !!}
            @endif

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="curriculum_id">Curriculum</label>
              </div>
              <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                <div class="form-group">
                  <div class="form-line{{ $errors->has('curriculum_id') ? ' error' : '' }}">
                    {!! Form::select('curriculum_id', $curriculum_id, null, ['class' => 'form-control selectpicker', 'required'=>'true'] ) !!}
                  </div>
                  @if ($errors->has('curriculum_id'))
                      <label class="error" for="curriculum_id">
                          {{ $errors->first('curriculum_id') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="code">Code</label>
              </div>
              <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                <div class="form-group">
                  <div class="form-line{{ $errors->has('code') ? ' error' : '' }}">
                    {!! Form::text('code', null, ['class'=>'form-control', 'pattern'=>'[A-Z]{0,1}', 'title'=>'Only One Capital Letter A - Z', 'required'=>'true' ]) !!}
                  </div>
                  @if ($errors->has('code'))
                      <label class="error" for="code">
                          {{ $errors->first('code') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="outcome">Outcome Name</label>
              </div>
              <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                <div class="form-group">
                  <div class="form-line{{ $errors->has('outcome') ? ' error' : '' }}">
                    {!! Form::text('outcome', null, ['class'=>'form-control', 'pattern'=>'[A-Z a-z]{4,30}', 'title'=>'Only Letters minimum 4 - 30 character', 'required'=>'true' ]) !!}
                  </div>
                  @if ($errors->has('outcome'))
                      <label class="error" for="outcome">
                          {{ $errors->first('outcome') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="description">Description</label>
              </div>
              <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                <div class="form-group">
                  <div class="form-line{{ $errors->has('description') ? ' error' : '' }}">
                    {!! Form::textarea('description', null, ['class'=>'form-control', 'required'=>'true']) !!}
                  </div>
                  @if ($errors->has('description'))
                      <label class="error" for="description">
                          {{ $errors->first('description') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>

            <div class="row clearfix">
              <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                <input type="submit" class="btn btn-primary m-t-15 waves-effect" value="Simpan">
              </div>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- #END# Horizontal Layout -->

</div>
@endsection

@section('css')
<link href="{{ asset('plugins') }}/bootstrap-select/css/bootstrap-select.css" rel="stylesheet">
@endsection

resources/views/curriculum/outcomes/index.blade.php
@extends('layouts.app')

@section('submenu')
  @include('curriculum.submenu')
@endsection

@section('content')

<div class="container-fluid outcomes-section">

  <div class="row clearfix">

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

      <div class="card">

        <ol class="breadcrumb breadcrumb-bg-blue-grey">
          <li><a href="/"><i class="material-icons">home</i> Home</a></li>
          <li class="active">Outcomes</li>
        </ol>

        <div class="body">
          <table class="table table-hover" id="konten"></table>
        </div>

      </div>
    </div>
  </div>
</div>

<div class="container-fluid competences-section" style='display:none'>

  <div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">

        <ol class="breadcrumb breadcrumb-bg-blue-grey">
          <li><a href="/"><i class="material-icons">home</i> Home</a></li>
          <li><a href="#" onclick="backToOutcomes()">Outcomes</a></li>
          <li class="active">A</li>
        </ol>

        <div class="body">
          <table class="table table-striped" id="competences"></table>
        </div>

      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
@endsection


@section('css')
<!-- JQuery DataTable Css -->
<link href="{{ asset('plugins') }}/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet">
<link href="{{ asset('plugins') }}/sweetalert/sweetalert.css" rel="stylesheet" />

<style>
#konten > tbody {
  cursor:pointer;
}

</style>
@endsection

@section('js')

<!-- Jquery DataTable Plugin Js -->
<script src="{{ asset('plugins') }}/jquery-datatable/jquery.dataTables.js"></script>
<script src="{{ asset('plugins') }}/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
<script src="{{ asset('plugins') }}/sweetalert/sweetalert.min.js"></script>

<script>

  var path = '{{ route("outcomes.index") }}';
  var path2 = '{{ route("competences.index") }}';

  function submenu(x) {
    table.ajax.url('?id='+x.value).load();
  }

  var table = $('#konten').DataTable({
    processing: true,
    serverSide: true,
    paging: false,
    ajax: '',
    columns: [
      { title: '#', data: 'no', name: 'no', searchable:false },
      { title: 'Code', data: 'code', name: 'code' },
      { title: 'Outcome', data: 'outcome', name: 'outcome' },
      { title: 'Description', data: 'description', name: 'description' },
      @if(\Laratrust::can("manage-outcomes"))
      { title: '', data: 'id', name: 'id', sortable: false, searchable: false,
          render: function(data) {
            return '<a href="'+path+'/'+data+'/edit"><button class="btn btn-primary btn-xs"><i class="material-icons">mode_edit</i></button></a> <button onclick="deleteData('+data+')" class="btn btn-danger btn-xs"><i class="material-icons">delete</i></button>';
          }
      }
      @endif
    ],
    responsive: true
  });

  $('#konten tbody').on('click', 'td', function () {

    var data = table.row($(this).closest('tr')).data();
    var indexColumn = table.cell(this).index().column;
    var lengthColumns = table.columns().header().length - 1;

    if (indexColumn != lengthColumns) {
      showCompetences(data.id);
    }    

  } );

  $.notify({ message: 'Click Row For More Information of Outcomes' });

  var tableCompetences;
  function showCompetences(id) {

    document.querySelector('.outcomes-section').style.display = 'none';
    document.querySelector('.competences-section').style.display = '';

    tableCompetences = $('#competences').DataTable({
      processing: true,
      serverSide: true,
      paging: false,
      ajax: path+'?outcome_id='+id,
      columns: [
        { title: '#', data: 'no', name: 'no', searchable:false },
        { title: 'Code', data: 'code', name: 'code' },
        { title: 'Competence', data: 'competence', name: 'competence' },
        { title: 'Level', data: 'title', name: 'title', render: function(data,type,full) {
          return '<a href="#" onclick="getLevel('+full.level_id+')">' + full.level + '. ' + data + '</a>';
        } },
        { title: 'Domain', data: 'domain', name: 'domain', render: function(data,type,full) {
          return '<a href="#" onclick="getDomain('+full.domain_id+')">' + data + '</a>';
        } },
        @if(\Laratrust::can("manage-competences"))
        { title: '', data: 'id', name: 'id', sortable: false, searchable: false,
            render: function(data) {
              return '<a href="'+path2+'/'+data+'/edit"><button class="btn btn-primary btn-xs"><i class="material-icons">mode_edit</i></button></a> <button onclick="deleteData2('+data+')" class="btn btn-danger btn-xs"><i class="material-icons">delete</i></button>';
            }
        }
        @endif
      ],
      responsive: true
    });
  }

  function getDomain(id) {
    $.ajax({
        url: '{{ route("domains.index") }}/'+id,
        type: 'GET',
        error: function() {
          alert('error');
        },
        success: function(res) {
          document.querySelector('.modal-title').innerHTML = res.domain;
          document.querySelector('.modal-body').innerHTML = '<p>'+res.description+'</p>';
          $('#myModal').modal();
        }
      });
  }

  function getLevel(id) {
    $.ajax({
        url: '{{ route("levels.index") }}/'+id,
        type: 'GET',
        error: function() {
          alert('error');
        },
        success: function(res) {
          document.querySelector('.modal-title').innerHTML = res.level+'. '+res.title;
          document.querySelector('.modal-body').innerHTML = '<p>'+res.description+'</p>';
          $('#myModal').modal();
        }
      });
  } 

  function backToOutcomes() {
    document.querySelector('.outcomes-section').style.display = '';
    document.querySelector('.competences-section').style.display = 'none';
    tableCompetences.destroy();
  }

  @if(\Laratrust::can("manage-outcomes"))
  function deleteData(id) {
    swal({
        title: "Are You Sure ?",
        text: "Data will be deleted!",
        type: "warning",
        showCancelButton: true,
        confirmButtonColor: "#DD6B55",
        confirmButtonText: "Ya, Hapus!",
        closeOnConfirm: false
    }, function() {
        sendAjax();
    } );

    function sendAjax() {
      $.ajax({
        url: path+'/'+id,
        data: { '_token': '{{ csrf_token() }}' },
        type: 'DELETE',
        error: function() {
          swal({
              title: "Failed !",
              text: "Please delete data which related to this outcome to continue",
              type: "error"
            });
        },
        success: function(res) {
            swal({
              title: "Deleted !",
              text: "Data has been deleted",
              type: "success"
            }, function() {
              location.reload();
            });
        }
      });
    }
  }
  @endif

  @if(\Laratrust::can("manage-competences"))
  function deleteData2(id) {
    swal({
        title: "Are You Sure ?",
        text: "Data will be deleted!",
        type: "warning",
        showCancelButton: true,
        confirmButtonColor: "#DD6B55",
        confirmButtonText: "Ya, Hapus!",
        closeOnConfirm: false
    }, function() {
        sendAjax();
    } );

    function sendAjax() {
      $.ajax({
        url: path2+'/'+id,
        data: { '_token': '{{ csrf_token() }}' },
        type: 'DELETE',
        error: function() {
          swal({
              title: "Failed !",
              text: "Please delete data which related to this competence to continue",
              type: "error"
            });
        },
        success: function(res) {
            swal({
              title: "Deleted !",
              text: "Data has been deleted",
              type: "success"
            }, function() {
              location.reload();
            });
        }
      });
    }
  }
  @endif

</script>
@endsection