routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', function () {
	return view('home');
})->name('home')->middleware('auth');

Route::get('/selectOrganization','SelectOrganizationController@index')->name('selectOrganization')->middleware('web','auth');
Route::get('/selectOrganization/{id}','SelectOrganizationController@show')->middleware('web','auth');

Route::group(['prefix'=>'apps/settings', 'middleware' => ['web','auth','organization'] ], function () {

	Route::post('roles/editRolePermission', 'Admin\RolesController@editRolePermission');

	Route::resource('users', 'Admin\UsersController');
	Route::resource('roles', 'Admin\RolesController');
	Route::resource('permissions', 'Admin\PermissionsController');

});

Route::group(['prefix'=>'apps', 'middleware' => ['web','auth','organization'] ], function () {

	Route::get('assesment/cohort/cummulative', 'Assesment\CohortController@cummulative');
	Route::get('assesment/student/cummulative', 'Assesment\StudentController@cummulative');

	Route::resource('assesment/course', 'Assesment\CourseController');
	Route::resource('assesment/outcome', 'Assesment\OutcomeController');
	Route::resource('assesment/cohort', 'Assesment\CohortController');
	Route::resource('assesment/curriculum', 'Assesment\CurriculumController');
	Route::resource('assesment/student', 'Assesment\StudentController');

	Route::resource('curriculum/attainments', 'Curriculum\AttainmentsController');
	Route::resource('curriculum/curriculums', 'Curriculum\CurriculumsController');
	Route::resource('curriculum/competences', 'Curriculum\CompetencesController');
	Route::resource('curriculum/components', 'Curriculum\ComponentsController');
	Route::resource('curriculum/courses', 'Curriculum\CoursesController');
	Route::resource('curriculum/domains', 'Curriculum\DomainsController');
	Route::resource('curriculum/grades', 'Curriculum\GradesController');
	Route::resource('curriculum/imports', 'Curriculum\ImportsController');
	Route::resource('curriculum/levels', 'Curriculum\LevelsController');
	Route::resource('curriculum/objectives', 'Curriculum\ObjectivesController');
	Route::resource('curriculum/outcomes', 'Curriculum\OutcomesController');
	Route::resource('curriculum/performances', 'Curriculum\PerformancesController');

	Route::resource('learning/classes', 'Learning\ClassesController');

});

app/Http/Controllers/Assesment/CurriculumController.php
<?php

namespace App\Http\Controllers\Assesment;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;
use App\Models\Curriculum;

class CurriculumController extends Controller
{

    private $program_id = 1;

    private $curriculums;

    public function __construct()
    {
      $this->curriculums = Curriculum::select('po_organizations.organization','pc_curriculums.id','pc_curriculums.title')
                          ->join('pc_programs','pc_programs.id','pc_curriculums.program_id')
                          ->join('po_organizations','po_organizations.id','pc_programs.organization_id')
                          ->where('program_id',$this->program_id)
                          ->orderBy('pc_curriculums.id','DESC')
                          ->orderBy('po_organizations.organization','ASC')
                          ->get();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      return view('assesment/curriculum', ['curriculums' => $this->curriculums ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $result = DB::table('pc_outcomes')
          ->select(DB::raw('pc_outcomes.code as outcome, smt, pc_courses.code as code, pc_courses.title_en as course, pa_directs.year, a1, a2, a3, a4'))
          ->join('pa_directs','pc_outcomes.id','pa_directs.outcome_id')
          ->join('pc_courses','pa_directs.course_id','pc_courses.id')
          ->orderBy('outcome', 'ASC')
          ->orderBy('smt', 'ASC')
          ->orderBy('pa_directs.code', 'ASC')
          ->orderBy('pa_directs.year', 'ASC')
          ->where('pc_outcomes.curriculum_id','=',$id)
          ->get();
        return response()->json($result);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

}

app/Http/Controllers/Curriculum/AttainmentsController.php
<?php

namespace App\Http\Controllers\Curriculum;

use Illuminate\Http\Request;
use App\Models\Attainment;
use App\Models\Curriculum;

use Yajra\DataTables\DataTables;
use Illuminate\Support\Facades\Session;
use DB;

class AttainmentsController extends \App\Http\Controllers\Controller
{


    private $validationRule = [
        'curriculum_id' => 'required|exists:pc_curriculums,id',
        'title' => 'required|between:1,100',
        'attainment' => 'required|integer|between:1,10',
        'treshold' => 'required|integer|between:1,100',
        'description' => 'required|between:1,240'
    ];

    public function index(Request $request)
    {
        $organization_id = $request->session()->get('organization_id');

        $curriculums = Curriculum::select('po_organizations.organization','pc_curriculums.id','pc_curriculums.title')
                        ->join('pc_programs','pc_programs.id','pc_curriculums.program_id')
                        ->join('po_organizations','po_organizations.id','pc_programs.organization_id')
                        ->where('po_organizations.id',$organization_id)
                        ->orderBy('pc_curriculums.id','DESC')
                        ->orderBy('po_organizations.organization','ASC')
                        ->get();

        if ($request->ajax()) {
            if(count($curriculums) > 0) {
                $curriculum_id = isset($_GET['id']) ? e($_GET['id']) : $curriculums[0]->id;
            } else {
                $curriculum_id = 0;
            }

            DB::statement(DB::raw('set @rownum=0'));

            $data = Attainment::select(DB::raw('@rownum  := @rownum  + 1 AS no'),'pc_attainments.*')
                            ->where('pc_attainments.curriculum_id',$curriculum_id);
            return Datatables::of($data)->make(true);
        }

        return view('curriculum.attainments.index',[ 'curriculums' => $curriculums ]);
    }

    public function create()
    {
        $organization_id = session()->get('organization_id');

        $curriculums = Curriculum::select('po_organizations.organization','pc_curriculums.id','pc_curriculums.title')
                        ->join('pc_programs','pc_programs.id','pc_curriculums.program_id')
                        ->join('po_organizations','po_organizations.id','pc_programs.organization_id')
                        ->where('po_organizations.id',$organization_id)
                        ->orderBy('pc_curriculums.id','DESC')
                        ->pluck('title','id');

        return view('curriculum.attainments.form',[ 
            'curriculum_id' => $curriculums, 
        ]);
    }

    public function store(Request $request)
    {
        $this->validate($request, $this->validationRule);

        $data = $request->all();

        $db = Attainment::create($data);

        Session::flash("status", [
            "level"=>"success",
            "message"=>"Data has been saved"
        ]);

        return redirect()->route('attainments.index');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $data = Attainment::find($id);

        $organization_id = session()->get('organization_id');

        $curriculums = Curriculum::select('po_organizations.organization','pc_curriculums.id','pc_curriculums.title')
                        ->join('pc_programs','pc_programs.id','pc_curriculums.program_id')
                        ->join('po_organizations','po_organizations.id','pc_programs.organization_id')
                        ->where('po_organizations.id',$organization_id)
                        ->orderBy('pc_curriculums.id','DESC')
                        ->pluck('title','id'); 
                               
        return view('curriculum.attainments.form', [ 
            'curriculum_id' => $curriculums,
            'data' => $data,
        ]);
    }

    public function update(Request $request, $id)
    {

        $this->validate($request, $this->validationRule);

        $data = $request->all();

        $db = Attainment::find($id);

        $db->update($data);

        Session::flash("status", [
            "level"=>"success",
            "message"=>"Data has been updated"
        ]);

        return redirect()->route('attainments.index');
    }

    public function destroy($id)
    {
        $db = Attainment::find($id);
        $db->delete();

        Session::flash("status", [
            "level"=>"danger",
            "message"=>"Data has been deleted"
        ]);

        return 'ok';
    }

}

app/Http/Controllers/Curriculum/CompetencesController.php
<?php

namespace App\Http\Controllers\Curriculum;

use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use Illuminate\Support\Facades\Session;

use App\Models\Curriculum;
use App\Models\Competence;
use App\Models\Domain;
use App\Models\Level;
use App\Models\Outcome;
use DB;


class CompetencesController extends \App\Http\Controllers\Controller
{


    private $validationRule = [
        'curriculum_id' => 'required|exists:pc_curriculums,id',
        'outcome_id' => 'required|exists:pc_outcomes,id',
        'level_id' => 'required|exists:pc_competence_levels,id',
        'code' => 'required|between:1,2',
        'competence' => 'required|between:1,250',
        'description' => 'required|between:1,250'
    ];

    public function index(Request $request)
    {
        $organization_id = $request->session()->get('organization_id');

        $curriculums = Curriculum::select('po_organizations.organization','pc_curriculums.id','pc_curriculums.title')
                          ->join('pc_programs','pc_programs.id','pc_curriculums.program_id')
                          ->join('po_organizations','po_organizations.id','pc_programs.organization_id')
                          ->where('po_organizations.id',$organization_id)
                          ->orderBy('pc_curriculums.id','DESC')
                          ->orderBy('po_organizations.organization','ASC')
                          ->get();

        if ($request->ajax()) {

            if(count($curriculums) > 0) {
                $curriculum_id = isset($_GET['id']) ? e($_GET['id']) : $curriculums[0]->id;
            } else {
                $curriculum_id = 0;
            }

            DB::statement(DB::raw('set @rownum=0'));

            $data = Competence::select(DB::raw('@rownum  := @rownum  + 1 AS no'),'pc_competences.*')
                        ->join('pc_outcomes','pc_competences.outcome_id','pc_outcomes.id')
                        ->where('pc_outcomes.curriculum_id',$curriculum_id);

            if($request->has('draw')) {
                return Datatables::of($data)->make(true);
            }

            return $data->get();
        }
    }

    public function create()
    {
        $organization_id = session()->get('organization_id');

        $curriculums = Curriculum::select('po_organizations.organization','pc_curriculums.id','pc_curriculums.title')
                        ->join('pc_programs','pc_programs.id','pc_curriculums.program_id')
                        ->join('po_organizations','po_organizations.id','pc_programs.organization_id')
                        ->where('po_organizations.id',$organization_id)
                        ->orderBy('pc_curriculums.id','DESC')
                        ->pluck('title','id');

        $levels = [];

        foreach(Domain::get() as $v) {
            $levels[$v->domain] = Level::where('domain_id',$v->id)->get();
        }

        return view('curriculum.competences.form',[ 
            'curriculum_id' => $curriculums, 
            'levels' => $levels,
        ]);
    }

    public function store(Request $request)
    {
        $this->validate($request, $this->validationRule);

        $data = $request->all();

        $db = Competence::create($data);

        Session::flash("status", [
            "level"=>"success",
            "message"=>"Data has been saved"
        ]);
        
        return redirect()->route('outcomes.index');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {

        $data = Competence::find($id);
        $outcome = Outcome::find($data->outcome_id);
        $data['curriculum_id'] = $outcome->curriculum_id;
        
        $organization_id = session()->get('organization_id');

        $curriculums = Curriculum::select('po_organizations.organization','pc_curriculums.id','pc_curriculums.title')
                        ->join('pc_programs','pc_programs.id','pc_curriculums.program_id')
                        ->join('po_organizations','po_organizations.id','pc_programs.organization_id')
                        ->where('po_organizations.id',$organization_id)
                        ->orderBy('pc_curriculums.id','DESC')
                        ->pluck('title','id');

        $levels = [];

        foreach(Domain::get() as $v) {
            $levels[$v->domain] = Level::where('domain_id',$v->id)->get();
        }

        return view('curriculum.competences.form', [ 
            'curriculum_id' => $curriculums,
            'data' => $data,
            'levels' => $levels,
        ]);
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, $this->validationRule);

        $data = $request->all();

        $db = Competence::find($id);

        $db->update($data);

        Session::flash("status", [
            "level"=>"success",
            "message"=>"Data has been updated"
        ]);

        return redirect()->route('outcomes.index');
    }

    public function destroy($id)
    {
        $db = Competence::find($id);
        $db->delete();

        Session::flash("status", [
            "level"=>"danger",
            "message"=>"Data has been deleted"
        ]);

        return 'ok';
    }

}

app/Http/Controllers/Curriculum/CurriculumsController.php
<?php

namespace App\Http\Controllers\Curriculum;

use Illuminate\Http\Request;
use App\Models\Objective;
use Yajra\DataTables\DataTables;
use Illuminate\Support\Facades\Session;
use DB;


class CurriculumsController extends \App\Http\Controllers\Controller
{


    private $validationRule = [
        'curriculum_id' => 'required|exists:pc_curriculums,id',
        'objective' => 'required|unique:pc_competence_objectives,objective',
        'description' => 'required'
    ];

    public function index(Request $request)
    {

        if ($request->ajax()) {

            DB::statement(DB::raw('set @rownum=0'));

            $data = Objective::select(DB::raw('@rownum  := @rownum  + 1 AS no'),'pc_competence_objectives.*')
                              ->where('curriculum_id',$curriculum_id);
            return Datatables::of($data)->make(true);
        }

        return view('curriculum.objectives.index');
    }

    public function create()
    {
        return view('curriculum.objective.form');
    }

    public function store(Request $request)
    {
        $this->validate($request, $this->validationRule);

        $data = $request->all();

        $db = objective::create($data);

        Session::flash("status", [
            "level"=>"success",
            "message"=>"Berhasil Di Simpan"
        ]);

        return redirect()->route('curriculum.objectives.index');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $data = Role::find($id);

        return view('curriculum.objectives.form')->with(compact('data'));
    }

    public function update(Request $request, $id)
    {
        $this->validationRule['name'] = $this->validationRule['name'].','.$id; //exception unique rule for name
        $this->validate($request, $this->validationRule);

        $data = $request->all();

        $db = Role::find($id);

        $db->update($data);

        Session::flash("status", [
            "level"=>"success",
            "message"=>"Berhasil Di Simpan"
        ]);

        return redirect()->route('curriculum.objectives.index');
    }

    public function destroy($id)
    {
        $db = Role::find($id);
        $db->delete();

        Session::flash("status", [
            "level"=>"danger",
            "message"=>"Berhasil Di Hapus"
        ]);

        return 'ok';
    }

}

resources/views/curriculum/courses/form.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">

  <!-- Horizontal Layout -->
  <div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <ol class="breadcrumb breadcrumb-bg-blue-grey">
          <li><a href="/"><i class="material-icons">home</i> Home</a></li>
          <li><a href="{{ route('courses.index') }}">Courses</a></li>
          <li class="active">Add New Course</li>
        </ol>

        <div class="body">
            @if(isset($data))
              {!! Form::model($data, ['url' => route('courses.update', $data->id), 'files'=>true,'method'=>'put','class'=>'form-horizontal']) !!}
            @else
              {!! Form::open(['url' => route('courses.store'), 'method' => 'post','files'=>true, 'class'=>'form-horizontal']) !!}
            @endif

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="curriculum_id">Curriculum</label>
              </div>
              <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                <div class="form-group curriculum-selection">
                  <div class="form-line{{ $errors->has('curriculum_id') ? ' error' : '' }}">
                    {!! Form::select('curriculum_id', $curriculum_id, null, ['class' => 'form-control selectpicker','onchange'=>'updateCurriculum(this.value)', 'required'=>'true'] ) !!}
                  </div>
                  @if ($errors->has('curriculum_id'))
                      <label class="error" for="curriculum_id">
                          {{ $errors->first('curriculum_id') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="code">Code</label>
              </div>
              <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                <div class="form-group">
                  <div class="form-line{{ $errors->has('code') ? ' error' : '' }}">
                    {!! Form::text('code', null, ['class'=>'form-control', 'pattern'=>'[A-Z0-9]{2,10}', 'title'=>'Only Capital Letters minimum 2 - 10 character', 'required'=>'true' ]) !!}
                  </div>
                  @if ($errors->has('code'))
                      <label class="error" for="code">
                          {{ $errors->first('code') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="title_en">Title (english)</label>
              </div>
              <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                <div class="form-group">
                  <div class="form-line{{ $errors->has('title_en') ? ' error' : '' }}">
                  {!! Form::text('title_en', null, ['class'=>'form-control','placeholder'=>"Introduction to Engineering and Design II", 'pattern'=>'[A-Z a-z]{2,80}', 'title'=>'Only Letters minimum 2 - 80 character', 'required'=>'true' ]) !!}
                  </div>
                  @if ($errors->has('title_en'))
                      <label class="error" for="title_en">
                          {{ $errors->first('title_en') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="title">Title (indonesia)</label>
              </div>
              <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                <div class="form-group">
                  <div class="form-line{{ $errors->has('title') ? ' error' : '' }}">
                    {!! Form::text('title', null, ['class'=>'form-control','placeholder'=>"Pengantar Rekayasa Desain II", 'pattern'=>'[A-Z a-z]{2,80}', 'title'=>'Only Letters minimum 2 - 80 character', 'required'=>'true' ]) !!}
                  </div>
                  @if ($errors->has('title'))
                      <label class="error" for="title">
                          {{ $errors->first('title') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="credit">Credit</label>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-4 col-xs-8">
                <div class="form-group">
                  <div class="form-line{{ $errors->has('credit') ? ' error' : '' }}">
                  {!! Form::number('credit', null, ['class'=>'form-control', 'placeholder'=>'2 sks','min'=>'1', 'max'=>'8', 'required'=>'true' ]) !!}
                  </div>
                  @if ($errors->has('credit'))
                      <label class="error" for="credit">
                          {{ $errors->first('credit') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="semester">Semester</label>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-4 col-xs-8">
                <div class="form-group">
                  <div class="form-line{{ $errors->has('semester') ? ' error' : '' }}">
                  {!! Form::number('semester', null, ['class'=>'form-control', 'placeholder'=>'Semester 7','min'=>'1', 'max'=>'20', 'required'=>'true' ]) !!}
                  </div>
                  @if ($errors->has('semester'))
                      <label class="error" for="semester">
                          {{ $errors->first('semester') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="component_id">Component</label>
              </div>
              <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                <div class="form-group">
                  <div class="components_selection form-line{{ $errors->has('component_id') ? ' error' : '' }}">
                    {!! Form::select('component_id', [], null, ['class' => 'form-control selectpicker', 'required'=>'true'] ) !!}
                  </div>
                  @if ($errors->has('component_id'))
                      <label class="error" for="component_id">
                          {{ $errors->first('component_id') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="sylabus">Sylabus</label>
              </div>
              <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                <div class="form-group">
                  <div class="form-line{{ $errors->has('sylabus') ? ' error' : '' }}">
                    {!! Form::textarea('sylabus', null, ['class'=>'form-control']) !!}
                  </div>
                  @if ($errors->has('sylabus'))
                      <label class="error" for="sylabus">
                          {{ $errors->first('sylabus') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
              </div>
              <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                <div class="form-group">
                  <div class="checkbox">
                      <input name="compulsory" type="checkbox" id="Compulsory" class="filled-in" {{ !is_null(old('compulsory')) || isset($data->compulsory) && $data->compulsory ? 'checked' : '' }}>
                      <label for="Compulsory">Compulsory </label>
                      <input name="class" type="checkbox" id="Class" class="filled-in" {{ !is_null(old('class')) || isset($data->class) && $data->class ? 'checked' : '' }}>
                      <label for="Class">Class </label>
                      <input name="lab" type="checkbox" id="Lab" class="filled-in" {{ !is_null(old('lab')) || isset($data->lab) && $data->lab? 'checked' : '' }}>
                      <label for="Lab">Lab </label>
                      <input name="field" type="checkbox" id="Field" class="filled-in" {{ !is_null(old('field')) || isset($data->field) && $data->field ? 'checked' : '' }}>
                      <label for="Field">Field</label>
                  </div>
                  @if ($errors->has('compulsory'))
                      <label class="error" for="compulsory">
                          {{ $errors->first('compulsory') }}
                      </label>
                  @endif

                </div>
              </div>
            </div>

            <div class="row clearfix">
              <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                <label for="competences">Competences</label>
              </div>
              <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                <div class="form-group">
                  <div class="competences_selection form-line{{ $errors->has('competences') ? ' error' : '' }}">
                    <select class="form-control selectpicker" multiple data-live-search="true" required="true"></select>
                  </div>
                  @if ($errors->has('competences'))
                      <label class="error" for="competences">
                          {{ $errors->first('competences') }}
                      </label>
                  @endif
                </div>
              </div>
            </div>

            <div class="row clearfix">
              <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                <input type="submit" class="btn btn-primary m-t-15 waves-effect" value="Save">
              </div>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- #END# Horizontal Layout -->

</div>
@endsection

@section('js')
<script>

  var componentCt = document.querySelector('.components_selection');
  var competenceCt = document.querySelector('.competences_selection');

  @if(isset($data))
  var oldComponent_id = '{{ $data->component_id }}';
  var oldCompetence_id = {!! $data->competence_id !!};
  @else
  var oldComponent_id = '{{ old("component_id") }}';
  var oldCompetence_id = {!! old("competence_id") == null ? '[]' : json_encode(old("competence_id")) !!};
  @endif
  
  function sendAjax(path,cb) {
    $.ajax({
      url: path,
      error: function() {
        alert('error');
      },
      success: function(res) {
        cb(res);
      }
    });
  }

  function getComponents(id) {
    var path = '{{ route("components.index") }}/?id='+id;
    sendAjax(path, function(data) {
      var output = '<select class="form-control selectpicker" required="true" name="component_id">';

      data.forEach(function(v,i){
        output += '<option value="'+v.id+'" ';
        output += oldComponent_id == v.id ? 'selected="selected"' : ''; 
        output += '>'+v.code+'. '+v.component+'</option>';
      });

      output += '</select>';
      componentCt.innerHTML = output;

      $('.selectpicker').selectpicker(); //refresh list

    })
  }

  function getCompetences(id) {
    var path = '{{ route("competences.index") }}/?id='+id;
    sendAjax(path, function(data) {
      var output = '<select class="form-control selectpicker" multiple data-live-search="true" required="true" name="competence_id[]">';

      data.forEach(function(v,i){
        output += '<option value="'+v.id+'" ';

        oldCompetence_id.forEach(function(v2,i) {
          output += v2 == v.id ? 'selected="selected"' : '';
        })

        output += '>'+v.code+'. '+v.competence+'</option>';
      });

      output += '</select>';
      competenceCt.innerHTML = output;

      $('.selectpicker').selectpicker(); //refresh list

    })
  }

  function updateCurriculum(id) {
    getComponents(id);
    getCompetences(id);
  }

  updateCurriculum(document.querySelector('.curriculum-selection select').value);

</script>
@endsection